wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1724933556
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 95
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 95
      - 98
      - 105
      3:
      - 23
      4: 3.11.6
      5: 0.17.8
      6: 4.44.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
